name: Lighthouse CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install & Build
        run: |
          yarn install
          yarn build

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
        with:
          serverBaseUrl: "https://vtex-lhci-server.herokuapp.com/"
          serverToken: ${{ secrets.LHCI_TOKEN }}
          configPath: './lighthouserc.json'
